dist: trusty
language: go

cache:
  directories:
    - $GOPATH/pkg/dep

go:
  - 1.9

os:
  - linux

before_install:
  - go get github.com/mattn/goveralls

install:
  - make setup-ci

script:
  - make build-all-race-ci
  - make test-ci
  - make coveralls
