sudo: required

language: go

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/dep

go:
  - 1.8.3

os:
  - linux

before_install:
  - go get github.com/mattn/goveralls

install:
  - make setup-ci

script:
  - make build-all-race
  - make test
  - make coveralls
