sudo: required

language: go

services:
  - docker

go:
  - 1.8.1

os:
  - linux

before_install:
  - go get github.com/mattn/goveralls

install:
  - make setup-ci

script:
  - make build-all
  - make test-race
  - METALINTER_CONCURRENCY=1 make check
  - make coveralls
